### PR TITLE
WIP: front page update

### PR DESCRIPTION
**Pull request by nokome**
Basic structure of front-page redesign setup. More images and refinements of text to be done.

### CODE REVIEW

**Comment by apawlik** [comment]
reactive.png image missing.

**Comment by michael** [comment]
> Combine different skills in one document. Showcase your reproducible data-driven research without oversimplifying it.

These two sentences do not say much, at least to me. What do we want to say?

**Comment by michael** [comment]
It's just my opinion but I don't like to read marketing-ish lingo on open source projects websites.

> Leverage the power of data manipulation...

> Connecting coding expertise with research knowledge

Maybe some wordings can be made just a bit more straight. ;)

**Comment by apawlik** [comment]
> Combine different skills in one document. Showcase your reproducible data-driven research without oversimplifying it.

This again is very research (academic) specific. I know that I am targeting a lot of this audience but they have a lot of interest in Stencila. I have already had a lot of feedback among researchers in the reproducible aspect and the fact that people with different expertise (some have more coding expertise, some have more domain expertise, some have both but that is not always the case) can work in one document. Hence the wording.

**Comment by nokome** [comment]
I preferred aspects of both @michael and @apawlik's text. So yesterday, I worked on combining parts from both. I should have committed and pushed my changes earlier!

I still think that this needs a work and perhaps help from someone who is a professional writer but I think it is fine for now.

> Combine different skills in one document. Showcase your reproducible data-driven research without oversimplifying it.

I think @apawlik was trying to express two aspects of connecting coders and non-coders:

- "combine different skills in one document" i.e. collaborating on one document to combine coder's data analysis skills and domain expert's subject knowledge

- "Showcase your reproducible data-driven research without oversimplifying it." : coders being able to make their sophisticated data analysis work more accessible to non-coders by easily presenting it into a familiar interface (ie sheet) or docs

These are important concepts to get across but I agree that we need better ways to express them.

**Comment by michael** [comment]
@apawlik @nokome also think we're getting close. Thanks for your work on this, and no worries regarding my suggestions... was just dumping thoughts off my brain. :)

**Pull request merged**
