### PR TITLE
initial draft of new Stencila-based Stencila website

### PR DESCRIPTION
**Pull request by xolotl**
Included is an initial draft of the new Stencila website, written using Stencila markup and affordances, to enable a deployment test and get initial feedback on the work so far.

The draft includes only a home page, included header/footer files, and a few images used in the draft.

## Notes
1. The copy here is a complete draft of all suggested copy for the home page, except what will be in the header and footer.
2. The images here are mostly placeholders.
3. The layout here is an approximation of a suggested layout, although there are still things to come related to text styling and the layout's responsive design.
4. This text here is basically unstyled as there are issues related to how to style text in a Stencila environment. For example: the font family and text size are default/unstyled.

## Unsolved Issues
1. ~~How to apply global text styles (eg, font family). Possible solutions already investigated:~~
    1. ~~Nesting a whole document in a Stencila style block does not seem to apply to all enclosed text.~~
    2. ~~Tailwind styles could be applied to every element in the document, but that would be messy as it would require the use of multiple Stencila style blocks and also application in multiple raw HTML blocks.~~
2. [Tailwind classes for responsive design](https://tailwindcss.com/docs/responsive-design) don't seem to work (eg, sm:flex-nowrap) which would be the easiest way to make the site responsive.
3. There was [one instance](https://github.com/xolotl/website/blob/e5a2f7a3bb3c3b8e003ca4232f3857e88bf4a783/index.md?plain=1#L12) where a Tailwind class (ie, m-0) did not have an effect and was overridden with a standard inline CSS rule (ie, style="margin:0;"). It's not clear why the Tailwind class didn't work.
4. Headers within raw HTML blocks do not appear in the upper right Stencila outline navigation ([see example](https://github.com/xolotl/website/blob/e5a2f7a3bb3c3b8e003ca4232f3857e88bf4a783/index.md?plain=1#L12)).

### CODE REVIEW

**Comment by xolotl** [comment]
This new commit addresses Issue 1, as I found a semi-elegant way to apply a default sans serif font family to the whole document, nesting most of the document within one Stencila style block. However, this exacerbates Issue 4 as now no headers appear in the upper right Stencila outline navigation (presumably because they are nested?).

This commit also moves files from .md to .smd.

**Comment by xolotl** [comment]
Obviously if we want to use a more specific font beyond system fonts (eg, from Google), we'd need a way to load that font into the doc.

**Comment by nokome** [comment]
Some responses to the issues

>  How to apply global text styles (eg, font family).

This is the intended role of themes. Currently there is only one theme: `default`. We have had several builtin themes in v1 and the intention is to reinstate support for users to select a theme. This includes a side/folder specific theme, say in a `theme.css` file.

> Tailwind classes for responsive design don't seem to work (eg, sm:flex-nowrap) which would be the easiest way to make the site responsive.

Could you post an issue in the stencila/stencila about this please.

> There was one instance where a Tailwind class (ie, m-0) did not have an effect and was overridden with a standard inline CSS rule (ie, style="margin:0;"). It's not clear why the Tailwind class didn't work.

Ditto

>  Headers within raw HTML blocks do not appear in the upper right Stencila outline navigation (see example).

This is unlikely to be ever supported. Stencila does not parse the content of `RawBlock`s and so does not know that header exist there.

**Comment by xolotl** [comment]
I thought that I was seeing the preview without the Stencila upper right outline navigation, but when I looked again today, the navigation was showing both via preview and serve, so what I saw yesterday must have been some anomaly that I can't recreate now, so taking it off the list off issues.

**Comment by nokome** [comment]
As discussed, I decided to start off with something simpler and build from there. So will close this now but will certainly come back to it later to pull content out.

**Pull request closed without merging**
